[package]
name = "familiar-runtime"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
familiar-core.workspace = true
familiar-platform.workspace = true

[dev-dependencies]
familiar-advisor.workspace = true
familiar-platform = { workspace = true, features = ["testkit"] }
